# Generated by Django 3.2.4 on 2021-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Cluster', models.CharField(max_length=200)),
                ('Business', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Equipment_Type', models.CharField(max_length=200)),
                ('Item_Type', models.CharField(max_length=200)),
                ('Ownership', models.CharField(max_length=200)),
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('NumberofmonthstheitemhasbeeninApttus', models.CharField(max_length=200)),
                ('Itemequalorlessthan12monthsold', models.CharField(max_length=200)),
                ('OITContribution_18m', models.CharField(default='nill', max_length=200)),
            ],
        ),
    ]
