# Generated by Django 3.2.4 on 2021-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0002_remove_product_oitcontribution_18m'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='OITContribution_18m',
            field=models.CharField(default='nill', max_length=200),
        ),
    ]
