# Generated by Django 3.2.4 on 2021-06-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0003_product_oitcontribution_18m'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='OITContribution_36m',
            field=models.CharField(default='nill', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='OITValue_18mo',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='OITValue_36mo',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='Orderedinthelast_18m',
            field=models.CharField(default='nill', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='Orderedinthelast_36m',
            field=models.CharField(default='nill', max_length=200),
        ),
    ]
