# Generated by Django 3.2.4 on 2021-06-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0006_auto_20210616_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
