# Generated by Django 3.2.4 on 2021-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0007_auto_20210616_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Catalog_release',
            field=models.CharField(default='nill', max_length=200),
        ),
    ]
