# Generated by Django 3.2.4 on 2021-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0008_product_catalog_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('Catalog_release', models.CharField(default='nill', max_length=200)),
                ('Cluster', models.CharField(max_length=200)),
                ('Business', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Equipment_Type', models.CharField(max_length=200)),
                ('Item_Type', models.CharField(max_length=200)),
                ('Ownership', models.CharField(max_length=200)),
                ('Product_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('NumberofmonthstheitemhasbeeninApttus', models.CharField(max_length=200)),
                ('Itemequalorlessthan12monthsold', models.CharField(max_length=200)),
                ('OITContribution_18m', models.CharField(default='nill', max_length=200)),
                ('OITValue_18mo', models.CharField(default='nill', max_length=200)),
                ('OITContribution_36m', models.CharField(default='nill', max_length=200)),
                ('OITValue_36mo', models.CharField(default='nill', max_length=200)),
                ('Orderedinthelast_18m', models.CharField(default='nill', max_length=200)),
                ('Orderedinthelast_36m', models.CharField(default='nill', max_length=200)),
            ],
        ),
    ]
