# Generated by Django 3.2.4 on 2021-06-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0009_productdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
