# Generated by Django 3.2.4 on 2021-06-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0010_delete_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='NumberofmonthstheitemhasbeeninApttus',
            field=models.IntegerField(default=0),
        ),
    ]
