# Generated by Django 3.2.4 on 2021-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0011_alter_product_numberofmonthstheitemhasbeeninapttus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.CharField(max_length=200),
        ),
    ]
