# Generated by Django 3.2.4 on 2021-06-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0012_auto_20210616_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('Sales_Doc_Number', models.IntegerField(default=0)),
                ('Year_Month', models.CharField(default='nill', max_length=200)),
                ('Market', models.CharField(default='nill', max_length=200)),
                ('Business', models.CharField(default='nill', max_length=200)),
                ('Category', models.CharField(default='nill', max_length=200)),
                ('Product_Name', models.IntegerField(primary_key=True, serialize=False)),
                ('Options', models.CharField(default='nill', max_length=200)),
                ('WRP', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Option_Name', models.CharField(default='nill', max_length=200)),
                ('OIT_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Quantity', models.IntegerField(default=0)),
                ('Bundle_Marker_Flag', models.CharField(default='N', max_length=3)),
                ('Sales_Order_with_Bundle', models.CharField(default='N', max_length=3)),
                ('Product_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebapp.product', to_field='Product_id')),
            ],
        ),
    ]
